import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/tracker/widgets/tracker_drink_reminders_stepper_widget/tracker_drink_reminders_stepper_widget_cubit.dart';

class TrackerDrinkRemindersStepperWidgetController extends BaseController<TrackerDrinkRemindersStepperWidgetCubit>{}