import 'package:beebloom_water_tracker/app/core/controllers/base_modal_controller.dart';
import 'package:beebloom_water_tracker/app/tracker/widgets/tracker_task_activity_records_between_modal/tracker_task_activity_records_between_modal_cubit.dart';

class TrackerTaskActivityRecordsBetweenModalController
    extends BaseModalController<TrackerTaskActivityRecordsBetweenModalCubit> {}
