import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/tracker/widgets/tracker_notification_toggle_btn_widget/tracker_notification_toggle_btn_widget_cubit.dart';

class TrackerNotificationToggleBtnWidgetController extends BaseController<TrackerNotificationToggleBtnWidgetCubit>{

}