// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0BU0a2oGw0KqxFDtFHdCmJdY5z5zsu2o',
    appId: '1:185786555221:web:48b6e0a6e89f5fefc9eddc',
    messagingSenderId: '185786555221',
    projectId: 'beebloomwatertracker',
    authDomain: 'beebloomwatertracker.firebaseapp.com',
    storageBucket: 'beebloomwatertracker.appspot.com',
    measurementId: 'G-3NNMKJ583G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4UdtKo3QP3PEL4GCEanagPFd5Hitp0c',
    appId: '1:185786555221:android:603f97f20181666ec9eddc',
    messagingSenderId: '185786555221',
    projectId: 'beebloomwatertracker',
    storageBucket: 'beebloomwatertracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTV_qveWdx06stT0eiIGzsI32gJi4Tts',
    appId: '1:185786555221:ios:083780f75b1e5011c9eddc',
    messagingSenderId: '185786555221',
    projectId: 'beebloomwatertracker',
    storageBucket: 'beebloomwatertracker.appspot.com',
    iosClientId: '185786555221-1i5tc6dvtrpk6i4qc6nuud541e31t12l.apps.googleusercontent.com',
    iosBundleId: 'com.sevendotss.beebloomWaterTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTV_qveWdx06stT0eiIGzsI32gJi4Tts',
    appId: '1:185786555221:ios:03ddd68c41bf35b3c9eddc',
    messagingSenderId: '185786555221',
    projectId: 'beebloomwatertracker',
    storageBucket: 'beebloomwatertracker.appspot.com',
    iosClientId: '185786555221-rqlj62gnelnaorao05s56sr1ma9o6o4c.apps.googleusercontent.com',
    iosBundleId: 'com.sevendotss.beebloomWaterTracker.RunnerTests',
  );
}
