import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/tracker/widgets/tracker_get_next_plan_routine_by_user_account/tracker_get_next_plan_routine_by_user_account_cubit.dart';

class TrackerGetNextPlanRoutineByUserAccountController extends BaseController<TrackerGetNextPlanRoutineByUserAccountCubit>{}

